import { useSession } from 'next-auth/react';
import React, { useEffect, useRef, useState } from 'react'
import toast from 'react-hot-toast'
import { FaArrowRight } from 'react-icons/fa'
import { useProject } from './context/ProjectProvider';


interface currentprompt {
    id: string,
    projectid: string,
    projectName: string,
    text: string,
    code: string
}

interface props {
    currentprompt: currentprompt | null,
    setprojecttoggle: React.Dispatch<React.SetStateAction<boolean>>
}



function Promptinput({ currentprompt, setprojecttoggle }: props) {
    const textref = useRef<HTMLTextAreaElement>(null);
    const [suggestion, setsuggestion] = useState<string[] | null>(null)
    const [suggesstionloader, setsuggesstionloader] = useState<boolean>(false)
    const [loading, setloading] = useState<boolean>(false)
    const { data: session } = useSession();
    const { prompt, setprompt, setprojectdetails, setjsxgeneratedcode } = useProject();

    // codeextrator to extract only code that is generated by AI with startdelimeter jsxcode and enddelimeter #endjsxcode

    const codeextrator = (language: string, code: string): string | null => {
        const startdelimeter: string = language;
        const enddelimeter: string = `#end${language}`;

        const startindex: number = code.indexOf(startdelimeter);

        const endindex: number = code.indexOf(enddelimeter);

        if (startindex !== -1 && endindex !== -1) {
            const adjustedindex: number = startindex + startdelimeter.length;
            const extractedcode: string = code.slice(adjustedindex, endindex);
            return extractedcode;
        } else {
            return null;
        }
    }


    // set textref value to the prompt

    useEffect(() => {
        if (textref.current?.value !== prompt) {
            textref.current!.value = prompt;
        }
    }, [prompt])

    // fetch api call to generate the code by AI.

    const generate = async (prompt: string) => {
        setloading(true)
        try {
            const res = await fetch("/api/chat", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({ prompt })
            });

            const data = await res.json();

            if (res.status === 200) {
                const jsxcode: string | null = await codeextrator("htmlcode", data.text);
                if (jsxcode) {
                    setjsxgeneratedcode(jsxcode);
                    addprompt(prompt, jsxcode)
                }
                setloading(false);
            } else if (res.status === 400 || res.status === 500) {
                toast.error(data.message)
                setloading(false)
            }
        } catch (err) {
            console.error(err);
            toast.error("Server Error");
            setloading(false);
        }
    };

    // fetch api call to generate suggestions for users by AI.

    const generatesuggestions = async (prompt: string) => {
        try {
            setsuggesstionloader(true)
            const res = await fetch("/api/suggestion", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({ prompt })
            })
            const data = await res.json();
            if (res.status === 200) {
                setsuggestion(data.suggestions);
                setsuggesstionloader(false);
            } else if (res.status === 500 || res.status === 400) {
                toast.error(data.message);
                setsuggesstionloader(false);
            }
        } catch (err) {
            console.error(err);
            toast.error("Server error")
        }
    }

    // actions when user clicks generate.

    const handletext = async (): Promise<void> => {
        const inputvalue = textref.current?.value;

        if (inputvalue) {
            if (currentprompt) {
                setprompt(inputvalue);
                await generate(inputvalue);
                await generatesuggestions(inputvalue);
            } else {
                setprojecttoggle(true);
            }
        }
    }



    // fetch api call for adding new prompt to a specific project.

    const addprompt = async (text: string, code: string) => {
        try {
            const res = await fetch("/api/createprompt", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify({ prompt: { text, code, id: currentprompt?.id }, projectid: currentprompt?.projectid })
            })
            const data = await res.json();
            if (res.status === 200) {
                setprojectdetails((prev) => {
                    if (!prev) return [data.updatedproject]
                    return prev?.map((proj) => {
                        return proj._id === data.updatedproject._id ? data.updatedproject : proj
                    })
                })
                localStorage.removeItem(`projects_${session?.user.id}`);
            } else if (res.status >= 400) {
                toast.error(data.message);
            }
        } catch (err) {
            console.error(err);
            toast.error("Server error");
        }
    }

    // when the user clicks on the suggestions prompt state will be updated.

    const handlesuggestion = (value: string) => {
        if (textref.current?.value === prompt) {
            setprompt(prompt + " \n" + value);
        } else {
            setprompt(textref.current?.value + " \n" + value);
        }
    }

    return (
        <div className="bg-light-white dark:bg-dark-input-outline border border-light-grey dark:border-dark-grey/20 rounded-md h-[60vh] xss:min-h-[45vh] xl:h-[60vh] lg:w-[50vw] p-2 flex flex-col justify-between gap-5">
            <div className="w-full h-full relative">
                <textarea ref={textref} className="bg-light-mediumgrey dark:bg-dark-input-box dark:border-dark-grey/20  border border-light-grey  w-full  resize-none p-4 h-full rounded-md focus:outline-none placeholder:xl:text-base xl:text-base xss:text-sm placeholder:xss:text-sm placeholder:text-light-darkgrey" placeholder="Describe your UI... e.g., a dashboard with 3 cards and a sidebar" />
                <button onClick={handletext} disabled={loading} className="bg-light-black text-light-white dark:bg-dark-white dark:border dark:border-dark-grey/20 hover:bg-light-black/90 hover:dark:bg-dark-white/90 dark:text-dark-black transition-all ease-in-out absolute bottom-5 right-5 px-8 py-3 lg:px-4 rounded-md  font-bold text-xl cursor-pointer  h-[7vh] lg:h-[5vh] xl:h-[6vh]  lg:w-[15vw] xl:w-[18vw] flex items-center lg:justify-center">
                    {loading ? <div className="animate-spin inline-block lg:mr-5 xss:size-4 border-3 border-light-darkgrey dark:border-dark-grey  border-t-light-white dark:border-t-dark-black rounded-full " role="status" aria-label="loading">
                    </div> : <FaArrowRight className="lg:hidden" />}<div className="hidden lg:flex lg:items-center lg:gap-10 lg:justify-center lg:text-base xl:text-lg">{loading ? <>Generating </> : <>Generate</>}</div></button>
            </div>
            {suggesstionloader && <div className='flex gap-5 flex-wrap p-2'>
                <div className='w-52 h-1 dark:bg-dark-mediumgrey bg-light-mediumgrey rounded-full animate-pulse'></div>
                <div className='w-52 h-1 dark:bg-dark-mediumgrey bg-light-mediumgrey rounded-full animate-pulse'></div>
                <div className='w-52 h-1 dark:bg-dark-mediumgrey bg-light-mediumgrey rounded-full animate-pulse'></div>
            </div>}
            {!suggesstionloader && suggestion && suggestion?.length > 0 && <div className='flex gap-3 w-full flex-wrap'>
                {suggestion?.map((item, indx) => {
                    return <button key={indx} className='dark:bg-dark-input-box bg-light-lightgrey hover:bg-light-mediumgrey border-light-darkgrey/20 p-2 sm:min-w-48 xss:text-xs sm:text-sm rounded-full flex items-center justify-center border dark:border-dark-grey/20 hover:dark:bg-dark-input-box/50 transition-all ease-in-out cursor-pointer' onClick={() => handlesuggestion(item)}>{item}</button>
                })}
            </div>}

        </div>
    )
}

export default Promptinput
